### ISSUE TITLE
Machines don't replay requests

### ISSUE THREAD

**Issue by luizkowalski** [superfly/fly-ruby#26]
I deployed an app using Machines API. I followed the exact same structure for the app deployed with Nomad: 
* set `PRIMARY_REGION=fra`
* Added `fly-ruby` gem
* deployed a machine on `fra` and cloned on `gru`

every POST request returns 409 (as defined by the gem) but it is not replayed 

<img width="435" alt="image" src="https://user-images.githubusercontent.com/112706/209984401-2440af52-2c55-4843-936a-22b0833345ce.png">

not sure if this is by design or if this is something yet to come on Machines

**Comment by jsierles** [comment]
Hey, is still still happening? It would be best to post on the community forum to get more eyes on this: https://community.fly.io/

**Comment by luizkowalski** [comment]
hey joshua. I don't know, I had so many troubles with Machines that I just rolled back to V1 unfortunately 😞 feel free to close this one or leave in case someone else also notice this

**Comment by jsierles** [comment]
Hey, can you try this again? We now have many machines apps using `fly-replay`, and machines have come a long way since January. If you still have trouble, please do post on the forums. Thanks!

**Comment by luizkowalski** [comment]
Nice to know, will play around with and let you know! Thanks a lot!
