### ISSUE TITLE
Threshold-based replays need to send metadata in the replayed request

### ISSUE THREAD

**Issue by jsierles** [superfly/fly-ruby#3]
When replaying due to a write attempt, we want the replayed request to set a cookie on the client that will force replays for a period of time after that write. But if the replay is NOT a write attempt, and was a GET request triggered by this rule, it should NOT reset a cookie.

Currently, this is the behavior, and it results in all requests going to the primary region unless NO requests are made within the threshold.

To fix this, it would be helpful if the Fly route can accept something like the following response header:

`Fly-Replay: region=iad, reason=exception`

And then, on the replayed request:

`Fly-Replayed: source=<instance id>; reason=exception; region=<region>`

This is also needed to figure out when a replay has happened. Currently, we're[ using a hack that detects two timing values](https://github.com/soupedup/fly-ruby/blob/main/fly-ruby/lib/fly-ruby/regional_database.rb#L52) in `Fly-Dispatch-Start`.

**Comment by jeromegn** [comment]
I've just deployed a version that changes our set of headers like:
- `fly-replay`’s value may now include `state=<anything>`
- `fly-replay-src: instance=<id>;region=<region>;t=<microseconds since epoch>;state=<optional state>`
- `fly-dispatch-start`’s value now includes `instance=<id>`

**Comment by jsierles** [comment]
Done in #5
